name: signal-rest
services:
    signal-cli-rest-api:
        container_name: signal-api
        restart: always
          #ports:
          # - 8080:8080
        expose:
          - 8080
        env_file: "signal-rest.env"
        volumes:
            - ./signal-rest:/home/.local/share/signal-cli
        environment:
            - MODE=native
        image: bbernhard/signal-cli-rest-api
        networks:
          - containnet
networks:
  containnet:
    external: true
